version: '3.9'

services:
  db:
    image: postgres:16
    container_name: shodhacode-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: shodhacode-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: shodhacode-frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data: